### ISSUE TITLE
Warning when executing gtk-fortran program

### ISSUE THREAD

**Issue by waltbrainerd** [vmagnin/gtk-fortran#102]
I get the following warning whenever I execute a gtk-fortran / gtk program.
Any help? Thanks. The program seems to run OK.

(a.exe:5936): GLib-GObject-WARNING **: attempt to override closure->va_marshal (0000000063a489b0) with new marshal (0000000066712988)

Windows 10, gfortran 6.1, latest versions of gtk-fortran and gtk (as far as I can tell).
The gtk libs come from Msys2 and I compiled GTK-Fortran myself.

Here is a sample simple program (I get the msg with any program):

program ft_gtk_quiz

   use gtk_hl
   use gtk, only: gtk_init
   implicit none
   integer(kind=c_int) :: response
   type(c_ptr) :: quiz_window

   call gtk_init()

   quiz_window = hl_gtk_window_new()

   ! Display a window with a message
   ! and YES and NO buttons
   response = hl_gtk_message_dialog_show &
        (message = ["Is 2 + 3 = 5?"], &
         button_set = GTK_BUTTONS_YES_NO, &
         title = "FT_QUIZ"//c_null_char, &
         parent = quiz_window)

   if (response == GTK_RESPONSE_YES) then
      print *, "You are correct!"
   else
      print *, "Refresh your adding skills."
   end if

end program ft_gtk_quiz

$ gfortran *quiz.f90 $GTK

$ echo $GTK
-IC:\Fortran_Tools\include -LC:\Fortran_Tools\lib -lgtkfortran -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl

**Comment by vmagnin** [comment]
Hi Walt,
No such message under Linux Kubuntu 16.04 (gfortran 5.4.0, GLib 2.48.1) and Kubuntu 16.10 (gfortran 6.2.0, GLib 2.50.0).
I do not think this problem is due to gtk-fortran because this message seems present with other applications using GLib under Windows:

- http://gtk.10911.n7.nabble.com/gtkmm3-on-msys2-gives-quot-attempt-to-override-closure-gt-va-marshal-quot-td90005.html
- https://www.ruby-forum.com/topic/6879002

This message comes from line 918 in this GLib file:
https://github.com/GNOME/glib/blob/master/gobject/gclosure.c
But it is beyond my competences.

Can you post here the exact GLib / GTK versions you use ? If you try with other versions, please update this issue.
