### ISSUE TITLE
Gtk & Gtk-Fortran licensing

### ISSUE THREAD

**Issue by DrOli** [vmagnin/gtk-fortran#105]
We noticed that the gtk-fortran page lists GTK+ as being GPL, but our research shows GTK+ to be LGPL (e.g. this (https://github.com/jerryd/gtk-fortran/wiki) compared to this(https://www.gtk.org/)).  We wonder if we got it wrong, or ???

Is Gtk-Fortran GPL since GTK+ was believed to be GPL?

Is Gtk-Fortran available as LGPL or otherwise in a form that does not require derivative works to be GPL, for example to produce commercial Apps?

We had written a number of Gtk <-> Interfaces, but used a few from Gtk-Fortran for testing.  We are happy to write those overlapping interfaces from scratch if you have objections to making derivative apps commercial ... please advise.

**Comment by vmagnin** [comment]
gtk-fortran has been under the GNU GPL 3 since the beginning in 2011. The project was small and I was not (and am still not) a license expert. I was so happy to contribute to the free software adventure and the GPL choice seemed evident to me, although there was some discussions at that time:
https://github.com/jerryd/gtk-fortran/issues/24

I have since sometimes think about the LGPL, gtk-fortran being used by more people, and maybe it is time to discuss again license problems. Perhaps it would be more convenient to:
- keep the GPL 3 for the cfwrapper.py and other scripts generating gtk-fortran, and also the examples,
- put under LGPL 3 the files automatically generated by these scripts (*-auto.f90 files and some others absolutely needed files like gtk.f90). Files not generated by a human being should probably not be protected by GPL: after all, it is just automatically generated Fortran interfaces, not a creative work.

Concerning the High-Level gtk-hl*.f90 files, it is jtappin work, so human generated. So it could stay GPL.

But in fact, I do not know if and how a project can be distributed with files under various licenses (and what about binaries ?). I am interested if someone has some experience to share.

**Comment by jerryd** [comment]
From what I am reading, we should consider going to LGPL or the better Appache 2 license. This would require each of our contributors to agree to do so. GTK+ is currently LGPL. The gtk-fortran source use GTK but it is only an interface to it, not part of it. I think this would broaden its use considerably.

See https://www.gnu.org/licenses/license-recommendations.html

**Comment by jerryd** [comment]
I should mention we could contact FSF for an opinion.

**Comment by jerryd** [comment]
On 02/24/2018 11:22 AM, DrOli wrote:
> Cheers for that.
> 
> I guess the simplistic question is: If we create an "app" with GTKFortran,
> and decide to take it commercial, what happens?
> 
> Many thanks
> 
> DrO
> 

I am not a lawyer so you will have to read the licenses. Since 
gtk-fortran applies to GTK to be of any use, the GTK licenses would 
apply for an end use and I think it uses LPGL.

As I stated before, all contributors will have to agree.

Regards,

Jerry
