### ISSUE TITLE
branch renaming

### ISSUE THREAD

**Issue by bonanza** [vmagnin/gtk-fortran#118]
I suggest to make the gtk3 branch the master branch because in my view GTK+ 3 is most widely-used nowadays and I see no need to use GTK+ 2 for new projects.

Cheers,
Jens.

**Comment by vmagnin** [comment]
Hi Jens,
it is probably time, before GTK+ 4 is released (in 2019 ?).

The first thing is to define the steps to follow. I have found those informations on renaming branches (both locally and remotely):
https://gist.github.com/lttlrck/9628955
https://stackoverflow.com/questions/6591213/how-do-i-rename-a-local-git-branch#6591218

So for us, it should be:
```
git pull origin
git branch -m master gtk2              # Rename branch locally    
git push origin :master                 # Delete the old branch    
git push --set-upstream origin gtk2     # Push the new branch, set local branch to track the new remote
git branch -m gtk3 master               # Rename branch locally    
git push origin :gtk3                    # Delete the old branch    
git push --set-upstream origin master    # Push the new branch, set local branch to track the new remote
```

I think it would be better to test this procedure on a test repository before executing it on gtk-fortran.

We also need to think about other users: what will happen in their repositories when they pull ? 
- Their master branch will be probably updated with gtk3 instead of gtk2. Is there any means to warn them ?
- Will the new gtk2 branch be pulled locally with "git pull origin" ?
- What about their local gtk3 branch ? Will it be deleted ?

Final question: is it compulsory to have a master branch or could we have just a gtk2 branch and a gtk3 branch ? (and in the future a gtk4 branch)

**Comment by bonanza** [comment]
As far as I can see, the steps you suggested should be correct.

But if I understand [https://help.github.com/articles/setting-the-default-branch/](https://help.github.com/articles/setting-the-default-branch/) correctly, we don't have to name a branch "master". That means, we don't have to rename the gtk3 branch, but just set this branch as default. Maybe we could just rename the "master" branch to gtk2. Then we would have branches gtk2, gtk3, gtk4, ... and the default one could be the branch which belongs to GTK+ version predominantly used in current OS distributions.

It would be nice to warn users about change in default branch and renaming of current master branch, but I don't see an effective approach. However, I guess users will recognize it immediate next time they compile the library. I think, the usual user just downloads and compiles the library and all the others fork the project (or are involved). The latter should have no problems and the former will not have big trouble as long as they can download the desired version easily and obtain a working library.

**Comment by vmagnin** [comment]
Thanks for this information. So I guess we will have to ask Jerry D. to change the default branch when the new gtk2 branch will be pushed, because I do not see any "Settings" tab in my interface. Jerry is the owner and admin of the repository.

**Comment by vmagnin** [comment]
I have made some tests with a fake repository:
If you try to delete the default branch, you obtain an error message : _" ! [remote rejected] master (refusing to delete the current branch: refs/heads/master)"._ 

We must therefore make the gtk3 branch the default branch before deleting the remote master branch. The procedure would be:

1. Rename the local master branch as gtk2: `git branch -m master gtk2`
2. Then setting gtk3 as the default branch in GitHub (settings of the repository)
3. Deleting the remote master branch:  `git push origin :master`
4. Pushing the new local gtk2 branch:  `git push --set-upstream origin gtk2`

Note that in the repository settings we read _""The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch. "_
And when changing the default branch we read this message: _"Changing your default branch can have unintended consequences that can affect new pull requests and clones. "_

**Comment by vmagnin** [comment]
I have made gtk3 the default branch in the github repository settings.

Concerning the renaming of master=>gtk2, perhaps we could wait the creation of the gtk4 branch.

**Comment by vmagnin** [comment]
The master branch has been renamed gtk2:

- Rename the local master branch as gtk2:  `git branch -m master gtk2`
- Deleting the remote master branch:  `git push origin :master`
- Pushing the new local gtk2 branch:  `git push --set-upstream origin gtk2`
