### ISSUE TITLE
You can help: improve documentation for macOS

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/gtk-fortran#154]
You can help us improve the documentation by posting the commands needed to install and use gtk-fortran under macOS. 

I am not at all familiar with macOS. I know it's a Unix system but I do not know if there is some peculiarities concerning the use of CMake and make commands...

You can post here paragraphs that could be included on the main Wiki page in this section:
https://github.com/vmagnin/gtk-fortran/wiki#macos

**Comment by implicitall** [comment]
I have installed gtk-fortran on macOS. Currently, macOS only works with gfortran 7.5.0, or releases that happen after, because of the fix that has been mentioned in another issue. You need to build plplot so that it has been built with the same version of gfortran.

Here are the commands I used which rely on Homebrew, a common package system:
brew install gcc@7
ln -s /usr/local/Cellar/gcc@7/7.5.0/bin/gfortran-7 /usr/local/bin/gfortran
brew install gtk+3

Download plplot, build, and install. The PLD_xcairo setting needs to be off.
For plplot:
mkdir build && cd build
cmake .. -DPLD_xcairo=OFF
make
sudo make install

Now you can build gtk-fortran.
You need to export the pkg-config path:
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
Build and install normally:
make build && cd build
cmake ..
make
sudo make install

At some later time, perhaps the plplot package from Homebrew could be used if the module versions were from the same gfortran version. And eventually, the current release of gcc could be used from Homebrew. But for now, I believe you have to do all of these steps.

**Comment by vmagnin** [comment]
Hi @andrewbest ,
thank you for your contribution ! I have included it in the wiki:
https://github.com/vmagnin/gtk-fortran/wiki#macos

I am not sure to have understood why you are not affected by the bug mentioned here:
https://github.com/vmagnin/gtk-fortran/issues/115#issuecomment-486272883
Does the bug affects gfortran-8 but not gfortran-7 ?

**Comment by implicitall** [comment]
GCC backports their fixes to previous versions. It happened that the 7.5.0 maintenance release was officially released first. So the fixes happen in time, not necessarily version.
