### ISSUE TITLE
crazy versioning scheme

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [vmagnin/gtk-fortran#182]
Can you explain the versioning scheme? Is it 19.04 with gtk3.xx.yy or something more complex?

**Comment by vmagnin** [comment]
@Alessandro-Barbieri 
you will find some explanations here: https://github.com/vmagnin/gtk-fortran/issues/94
I agree this versioning scheme is probably not satisfying.

From a practical point of view, the releases are just milestones and you can generally use directly the last development version: just git clone the gtk3 branch.

The core of the library, the *-auto.f90 files, is updated typically once in a year, generally a few months after a new Ubuntu release.

**Comment by band-a-prend** [comment]
As I could see the versioning no longer binded to Ubuntu releases and more relies or closer to GTK+ versions, isn't it?

**Comment by vmagnin** [comment]
> As I could see the versioning no longer binded to Ubuntu releases and more relies or closer to GTK+ versions, isn't it?

@band-a-prend , as stated in the Wiki: _starting with the 4.0 release, gtk-fortran will follow a classical semantic versioning (major.minor.patch): gtk-fortran 4.0 is based on GTK 4.2 and GLib 2.68._ And gtk-fortran 4.1 is based on GTK 4.4. So, the gtk-fortran versioning is now decoupled from the Ubuntu versioning and the GTK versioning (although the major version will still correspond to the major GTK version). See https://semver.org/spec/v2.0.0.html

Apart simplicity, another reason is that gtk-fortran is now generated with Fedora instead of Ubuntu, because Fedora can be seen as the natural home of GNOME and GTK. It was the first distribution to embed the preversions of GTK 4.

For the latest GTK 3 versions, I have used the GTK versioning.
