### ISSUE TITLE
How to use gtkf-sketcher

### ISSUE THREAD

**Issue by ifemi** [vmagnin/gtk-fortran#232]
Hello everyone and hello @vmagnin ,

I can't seem to find any documentation on how to use gtkf-sketcher.

Kindly illustrate with and example how the gtkf-sketcher is used.

Many thanks

**Comment by vmagnin** [comment]
@ifemi,
you're right, even basic information about gtkf-sketcher is missing! Writing a tutorial could be a good idea. Although the future of this app is not clear: for the moment there is no plan to port Glade to GTK 4 and the GTK 4 version of gtkf-sketcher is missing some important features, because some GTK 3 API disappeared. See Issue https://github.com/vmagnin/gtk-fortran/issues/207

But concerning the gtk3 branch, here is a very basic manual to test gtkf-sketcher (and I will add it into the wiki):

- go into the `gtk-fortran/build/sketcher/` directory and run `./gtkf-sketcher`
- From its _File>Open_ menu, load the `example.glade` file available in the same directory (do not choose the `gtkf-sketcher.glade` which is the file used to build the GUI of gtkf-sketcher itself!).
- In the _Info_ tab, the content of the `example.glade` file is analyzed.
- Keep the default options available in the _Options_ tab and go directly to the _Output_ tab.
- Click on the _Write Files_ button.
- In the terminal, go inside the `gtk-fortran/build/sketcher/example` directory where gtkf-sketcher has generated the Fortran files of the example application.
- Compile and execute the example application: 
```bash
$ gfortran example.f90 -o example $(pkg-config --cflags --libs gtk-3-fortran)
$ ./example
```
You can then add code to manage each event of your GUI into the specified files.

**Comment by ifemi** [comment]
Very many thanks @vmagnin. I'd hoped that sketcher would make it easier for me to transition into using glades for FORTRAN gui developments. I will have to rollup my sleeves and learn the gtk-glade bindings.

Great work you are doing btw. Much appreciated

**Comment by vmagnin** [comment]
You have three solutions to create a GUI with gtk-fortran:
1. hard-coding the GUI in Fortran, inspiring yourself with the gtk-fortran examples,
2. using Glade (at least for GTK 3) to create a `.ui` file and use the GtkBuilder API,
3. or write yourself your `.ui` file and use the GtkBuilder API: https://developer.gnome.org/gtk3/stable/ch01s03.html

It's true that, in all cases, the learning curve is quite steep at the beginning. But it will become easier with time as you understand more deeply how GTK is working.
Note also that, in my opinion, it's better to learn from scratch (solution 1.). Glade can be useful if you use many widgets in your API, but if you don't master the GTK basics it will be probably difficult to write the callback functions.
